### ISSUE TITLE
This error occurred when I was running experiments in Docker

### ISSUE THREAD

**Issue by philtruing** [contract-ace/verify-openzeppelin#1]
$ scribble r1.sol --output-mode flat --output eval_r1/scribble.sol
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'path/posix'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/usea/.nvm/versions/node/v10.24.1/lib/node_modules/eth-scribble/dist/bin/scribble.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by nathan-duddles** [comment]
I am getting the same error.

**Comment by nathan-duddles** [comment]
It seems various changes are needed due to breaking changes with Scribble.

I was able to get past this error by installing the most recent version of node, per: https://www.npmjs.com/package/eth-scribble

Specifically:

```
nvm install v16.15.0
nvm use 16
npm install -g eth-scribble
```

The scribble command also requires an additional option now:

```
scribble o1.sol --output-mode flat --output eval_o1/scribble.sol --instrumentation-metadata-file eval_o1/metadata
```

After running the above, I switched back to the included node version:

```
node use 10
```

And this line in the [postprocess script](https://github.com/contract-ace/verify-openzeppelin/blob/master/scripts/postprocess_scribble.py) requires updating to match the new version number:

```
PRAGMA_PRE  = "pragma solidity 0.8.13;"
```

Update the above before executing:

```
python /home/usea/verify/scripts/postprocess_scribble.py scribble.sol scribble.clean.sol
```

(edit: formatting)

**Comment by philtruing** [comment]
> 由于 Scribble 的重大更改，似乎需要进行各种更改。
> 
> 我能够通过安装最新版本的节点来克服这个错误，每个：[https ://www.npmjs.com/package/eth-scribble](https://www.npmjs.com/package/eth-scribble)
> 
> 具体来说：
> 
> ```
> nvm install v16.15.0
> nvm use 16
> npm install -g eth-scribble
> ```
> 
> scribble 命令现在还需要一个附加选项：
> 
> ```
> scribble o1.sol --output-mode flat --output eval_o1/scribble.sol --instrumentation-metadata-file eval_o1/metadata
> ```
> 
> 运行上述后，我切换回包含的节点版本：
> 
> ```
> node use 10
> ```
> 
> [而后处理脚本](https://github.com/contract-ace/verify-openzeppelin/blob/master/scripts/postprocess_scribble.py)中的这一行需要更新以匹配新版本号：
> 
> ```
> PRAGMA_PRE  = "pragma solidity 0.8.13;"
> ```
> 
> 执行前更新上述内容：
> 
> ```
> python /home/usea/verify/scripts/postprocess_scribble.py scribble.sol scribble.clean.sol
> ```
> 
> （编辑：格式化）

Thanks for your reply. I have solved this problem.If you're following this project, I'd like to ask you a question:
I tried to install SmartACE from source,https://github.com/contract-ace/smartace
 i **build the project**
when i run 
`make`
I came across this mistake:
CMake Error at cmake/scripts/buildinfo.cmake:52 (message):
  Unable to determine commit hash.  Either compile from within git repository
  or supply a file called commit_hash.txt
Did that happen when you installed it?

**Comment by nathan-duddles** [comment]
I have not yet tried installing from source. If I try I can let you know.

Were you able to follow the manual or automatic steps in [experiments](https://github.com/contract-ace/verify-openzeppelin/tree/master/experiments) to replicate the study results?

After the fixes I posted above, I am able to execute the commands for Verification (Manual) / Property: O1 but:

`cmake ..`  has a CMake error for Klee. Here is the output:

```
usea@70689562ce2e:~/verify/contracts/ownable/eval_o1/pcmc/build
$ cmake ..
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:6 (find_package)


-- clang-format found: /usr/bin/clang-format-10
-- klee found: /home/usea/klee/bin/klee
-- klee include found: /home/usea/klee/include
CMake Warning at cmake/Klee.cmake:65 (message):
  llvm-link not found, as required by KLEE.
Call Stack (most recent call first):
  CMakeLists.txt:84 (include)


-- sea found: /home/usea/seahorn/bin/sea
-- llvm-dis found: /usr/bin/llvm-dis-10
-- Configuring done
CMake Error at cmake/Klee.cmake:138 (add_dependencies):
  The dependency target "klee_driver" of target "symbex" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:84 (include)


-- Generating done
-- Build files have been written to: /home/usea/verify/contracts/ownable/eval_o1/pcmc/build
```

Then when executing `time make verify`, it seems to hang:

```
usea@70689562ce2e:~/verify/contracts/ownable/eval_o1/pcmc/build
$ time make verify
Scanning dependencies of target verify
Yama executing command:
/home/usea/seahorn/bin/sea pf -O3 --inline --dsa=sea-cs-t --enable-indvar --enable-loop-idiom --horn-global-constraints=true --horn-singleton-aliases=true --horn-use-write=true -m64 -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET --show-invars /home/usea/verify/contracts/ownable/eval_o1/pcmc/libverify/verify_seahorn.c /home/usea/verify/contracts/ownable/eval_o1/pcmc/cmodel.c /home/usea/verify/contracts/ownable/eval_o1/pcmc/harness.c
/usr/bin/clang-10 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET -m64 -I/home/usea/seahorn/include -o /tmp/tmp-f9o7d1ej/verify_seahorn.bc /home/usea/verify/contracts/ownable/eval_o1/pcmc/libverify/verify_seahorn.c
/usr/bin/clang-10 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET -m64 -I/home/usea/seahorn/include -o /tmp/tmp-f9o7d1ej/cmodel.bc /home/usea/verify/contracts/ownable/eval_o1/pcmc/cmodel.c

```

Please let me know if you get a different result! Thanks!

(edit: typo)

**Comment by ScottWe** [comment]
> I have not yet tried installing from source. If I try I can let you know.
> 
> Were you able to follow the manual or automatic steps in [experiments](https://github.com/contract-ace/verify-openzeppelin/tree/master/experiments) to replicate the study results?
> 
> After the fixes I posted above, I am able to execute the commands for Verification (Manual) / Property: O1 but:
> 
> `cmake ..` has a CMake error for Klee. Here is the output:
> 
> ```
> usea@70689562ce2e:~/verify/contracts/ownable/eval_o1/pcmc/build
> $ cmake ..
> -- The CXX compiler identification is GNU 7.5.0
> -- The C compiler identification is GNU 7.5.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
>   /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:6 (find_package)
> 
> 
> -- clang-format found: /usr/bin/clang-format-10
> -- klee found: /home/usea/klee/bin/klee
> -- klee include found: /home/usea/klee/include
> CMake Warning at cmake/Klee.cmake:65 (message):
>   llvm-link not found, as required by KLEE.
> Call Stack (most recent call first):
>   CMakeLists.txt:84 (include)
> 
> 
> -- sea found: /home/usea/seahorn/bin/sea
> -- llvm-dis found: /usr/bin/llvm-dis-10
> -- Configuring done
> CMake Error at cmake/Klee.cmake:138 (add_dependencies):
>   The dependency target "klee_driver" of target "symbex" does not exist.
> Call Stack (most recent call first):
>   CMakeLists.txt:84 (include)
> 
> 
> -- Generating done
> -- Build files have been written to: /home/usea/verify/contracts/ownable/eval_o1/pcmc/build
> ```
> 
> Then when executing `time make verify`, it seems to hang:
> 
> ```
> usea@70689562ce2e:~/verify/contracts/ownable/eval_o1/pcmc/build
> $ time make verify
> Scanning dependencies of target verify
> Yama executing command:
> /home/usea/seahorn/bin/sea pf -O3 --inline --dsa=sea-cs-t --enable-indvar --enable-loop-idiom --horn-global-constraints=true --horn-singleton-aliases=true --horn-use-write=true -m64 -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET --show-invars /home/usea/verify/contracts/ownable/eval_o1/pcmc/libverify/verify_seahorn.c /home/usea/verify/contracts/ownable/eval_o1/pcmc/cmodel.c /home/usea/verify/contracts/ownable/eval_o1/pcmc/harness.c
> /usr/bin/clang-10 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET -m64 -I/home/usea/seahorn/include -o /tmp/tmp-f9o7d1ej/verify_seahorn.bc /home/usea/verify/contracts/ownable/eval_o1/pcmc/libverify/verify_seahorn.c
> /usr/bin/clang-10 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -DMC_USE_STDINT -DMC_USE_EXTERNAL_NONDET -m64 -I/home/usea/seahorn/include -o /tmp/tmp-f9o7d1ej/cmodel.bc /home/usea/verify/contracts/ownable/eval_o1/pcmc/cmodel.c
> ```
> 
> Please let me know if you get a different result! Thanks!
> 
> (edit: typo)

Hi Nathan. Thank you for pointing this out! This seems to be an issue with running `seahorn` from within Docker. If you kill the process after the first time it hangs, then it seems to work fine.

I will update the build script to work with the newest version of Scribble tomorrow. I'll also see if there is a better solution to the `time make verify` issue.

**Comment by ScottWe** [comment]
@nathan-duddles The dockerfile should hopefully work again.
